add authentication using external server
o360/backend pull request #17
Opened 2020-02-18 06:25 UTC by maximskripnik

2020-02-18 11:12 UTC, maximskripnik commented
I forgot to make the authentication with google optional. Let me fix that

2020-02-19 07:36 UTC, warlockrichard requested changes
Everything else is OK to me.

2020-02-19 07:36 UTC, warlockrichard commented on app/silhouette/SilhouetteModule.scala
> +      Seq(
How about `googleProvider.to(Seq)`?

2020-02-19 07:38 UTC, maximskripnik commented on app/silhouette/SilhouetteModule.scala
> +      Seq(
This is a template to add more providers latter on, starting from twitter, facebook and vk in the https://github.com/o360/backend/issues/9

2020-02-19 07:41 UTC, yaroslavdudchenko commented on app/silhouette/SilhouetteModule.scala
> +      Seq(
Ok, then `.flatten`?

2020-02-19 07:45 UTC, maximskripnik commented on app/silhouette/SilhouetteModule.scala
> +      Seq(
I don't see a difference at all, but if you find this more readable, let's do it this way

2020-02-19 08:02 UTC, yaroslavdudchenko commented on app/silhouette/SilhouetteModule.scala
> +      Seq(
Thanks

2020-02-19 08:02 UTC, warlockrichard approved these changes

2020-02-19 08:03 UTC, merged